---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ekart-backend
  namespace: ekart
  labels:
    app: ekart-backend
spec:
  to:
    kind: Service
    name: ekart-backend
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None